### ISSUE TITLE
Live watches are never terminated

### ISSUE THREAD

**Issue by derlaft** [lmangani/cLoki#109]
Steps to reproduce:

* Open logs "live stream"
* Close grafana window
* `WATCH` query looks to never be terminating, consuming quite a lot of server resources (even after cLoki restart)

Tested version: https://github.com/lmangani/cLoki/commit/c40d1d9664523e60964a8d0b9338575c0a6d4720, but happens for quite a number of commits already

```

SELECT
    query_id,
    query,
    elapsed
FROM system.processes
WHERE position(query, 'watcher') > 0

Query id: 6db0c5a6-1b5d-4c02-987b-d8fe3947c21a

┌─query_id─────────────────────────────┬─query────────────────────────────────────────────────────────────────────────────────────────┬──────elapsed─┐
│ 9228fc26-ddac-42a2-9dfc-6e9f1122e673 │ WATCH cloki.watcher_ad9229b2ad45b6849848f45ceae2b4 FORMAT JSONEachRow                        │ 37.239223475 │
└──────────────────────────────────────┴──────────────────────────────────────────────────────────────────────────────────────────────┴──────────────┘
```

**Comment by lmangani** [comment]
@akvlad could you confirm this one?

**Comment by lmangani** [comment]
Thanks @derlaft for your useful report we're looking into this and will confirm when a fix is ready to test

**Comment by adubovikov** [comment]
@derlaft can you please provide the version of CH ?

**Comment by akvlad** [comment]
Hello @derlaft . The LIVE VIEW functionality was hidden behind the `EXPERIMENTAL=1` env variable .
https://github.com/lmangani/cLoki/pull/110 should fix.

**Comment by derlaft** [comment]
>The LIVE VIEW functionality was hidden behind the EXPERIMENTAL=1 env variable .
> https://github.com/lmangani/cLoki/pull/110 should fix.

Awesome, thanks a lot.

> but the underlying problem seems to be an actual bug the [LIVE VIEW](https://clickhouse.com/docs/en/sql-reference/statements/create/view/#live-view) experimental feature in clickhouse-server as it can be reproduced without cloki using just regular commands against the TIMEOUT setting.

Suspected something like that. Will try to open an issue.

**Comment by derlaft** [comment]
I think I found the source issue:

> The [JSONEachRowWithProgress](https://clickhouse.com/docs/en/interfaces/formats/#jsoneachrowwithprogress) format should be used when watching [LIVE VIEW](https://clickhouse.com/docs/en/sql-reference/statements/create/view/#live-view) tables over the HTTP interface. The progress messages will be added to the output to keep the long-lived HTTP connection alive until the query result changes. The interval between progress messages is controlled using the [live_view_heartbeat_interval](https://clickhouse.com/docs/en/sql-reference/statements/create/view/#live-view-settings) setting.

When this format is used, `WATCH` is terminated successfully after some inactivity from the client side.

**Comment by akvlad** [comment]
@derlaft , the JSONEachRowWithProgress format is applied in cLoki. Thanks for the advice.

**Comment by lmangani** [comment]
Reopen pending https://github.com/lmangani/cLoki/pull/110

**Comment by lmangani** [comment]
Merged! Thanks @akvlad for taking this to the finish line
