### ISSUE TITLE
Export Usage Metrics

### ISSUE THREAD

**Issue by lmangani** [lmangani/cLoki#11]
cLoki should collect and report Prometheus metrics about inserts, queries per label, and uptime.
Example: https://github.com/ricoberger/loki_exporter

**Comment by omartheironman** [comment]
was there any updates on this? we are also looking to track usage metrics from cloki and performance

**Comment by lmangani** [comment]
In the nodejs version we're currently measuring performance statistics using clickhouse, but this effort should be revived indeed now that we support telemetry as well alongside uptrace.

**Comment by lmangani** [comment]
@omartheironman feel free to give https://github.com/metrico/qryn/pull/174 a try and let us know if it helps at all

**Comment by lmangani** [comment]
Update: merged into qryn@2.1.4 
You can enable the /metrics endpoint using the `FASTIFY_METRICS` ENV variable
