### ISSUE TITLE
Unable to ingest events with up to date cLoki:latest docker image

### ISSUE THREAD

**Issue by faust93** [lmangani/cLoki#111]
Using logstash with logstash-output-loki plugin:
```
output {
  loki {
    url => "http://<REDACTED>:3100/loki/api/v1/push"
    message_field => "payload"
    batch_size => 1001024
  }
}
```
cLoki logs:
{"level":20,"time":1644311903345,"pid":20,"hostname":"8963e215248b","name":"cloki","reqId":"req-l","msg":"POST /loki/api/v1/push"}
{"level":30,"time":1644311903418,"pid":20,"hostname":"8963e215248b","name":"cloki","reqId":"req-l","res":{"statusCode":204},"responseTime":85.98648452758789,"msg":"request completed"}
{"level":30,"time":1644311903472,"pid":20,"hostname":"8963e215248b","name":"cloki","reqId":"req-m","req":{"method":"POST","url":"/loki/api/v1/push","hostname":"REDACTED:3100","remoteAddress":"10.202.108.131","remotePort":34545},"msg":"incoming request"}

For some reason I get 'statusCode:204' and looks like that's true since no events can be found in the db backend

With yesterday's image I'm able to ingest and see all the events. cLoki log looks like this:
```
POST /loki/api/v1/push
QUERY:  [Object: null prototype] {}
BODY:  {
  streams: [
    { stream: [Object], values: [Array] },
    { stream: [Object], values: [Array] },
     ......
```

**Comment by lmangani** [comment]
Thanks for your report @faust93 

> With yesterday's image I'm able to ingest and see all the events.

I'm not 100% sure I understand, are you saying the issue has been resolved with the latest releases of cloki?
A major protobuf fix has been committed yesterday and might have affected your scenario positively.

If that's not the case - The 204 would suggest those inserts pass the cloki push API properly.
Do you see any errors emitted by clickhouse-server as you're pushing data.

**Comment by faust93** [comment]
> I'm not 100% sure I understand, are you saying the issue has been resolved with the latest releases of cloki?

Opposite way. Issue has appeared with the latest release. I have cLoki docker image pulled yesterday and everything works as expected but with the latest image (qxip/cloki:latest pulled today) - does not. 

Weird is that I do not see any errors in clickhouse logs, looks like things are fetched, merged etc and moreover - the data is there, select * from samples_read limit 10 shows me the log items ingested. 
But any requests from Grafana or curl give "500 Internal server error", for ex:
```
curl localhost:3100/loki/api/v1/label
{"statusCode":500,"error":"Internal Server Error","message":"Internal Server Error"}
```

With the old cLoki image it gives this:
```
curl localhost:3100/loki/api/v1/label
{"status":"success","data":["service_identifier","host","logger","environment","application_name","service_unit"]}
```

**Comment by lmangani** [comment]
Bug replicated, fix in progress

**Comment by lmangani** [comment]
@faust93 release [v1.3.20](https://github.com/lmangani/cLoki/commit/ee7b8ae46fb452e105eb4c558935684b1a31b503) should address this problem. CI builds of containers has completed just now. Could you kindly try and confirm?

**Comment by faust93** [comment]
> @faust93 release [v1.3.20](https://github.com/lmangani/cLoki/commit/ee7b8ae46fb452e105eb4c558935684b1a31b503) should address this problem. CI builds of containers has completed just now. Could you kindly try and confirm?

It works! Thx!

**Comment by lmangani** [comment]
Thanks again for your report, and glad to have you in our users community!
