### ISSUE TITLE
Fingerprinting hashing algorimth is prone to collisions

### ISSUE THREAD

**Issue by derlaft** [lmangani/cLoki#113]
After ingesting logs from the k8s cluster for quite some time I've noticed some strange results. When I was querying for one specific label, I was getting results which should clearly belong to a completely different one.

Some digging showed that the problem is collision:

```:) select date, fingerprint, hex(MD5(labels)) from time_series where fingerprint=523712935;

┌───────date─┬─fingerprint─┬─hex(MD5(labels))─────────────────┐
│ 2022-02-09 │   523712935 │ A2494F27CF46F29BCD88809CE8267F23 │
│ 2022-02-04 │   523712935 │ 57F427CE06BD67AC5E45BF62F94A5177 │
└────────────┴─────────────┴──────────────────────────────────┘
```

This is the current fingerprinting code:

https://github.com/lmangani/cLoki/blob/c40d1d9664523e60964a8d0b9338575c0a6d4720/lib/utils.js#L21-L26

It goes all the way here:

https://github.com/MatthewBarker/hash-string/blob/master/source/hash-string.js#L6-L16

It looks to me it's very suboptimal, since very fast, efficient, and much less prone for collisions hashes do exist. For example, xxHash64, also available in js: https://www.npmjs.com/package/xxhashjs.

**Comment by derlaft** [comment]
Hmmm - looks like original loki uses some kind of fingerprint mapping: https://github.com/grafana/loki/blob/a3bacd5739da2d41f3f9a2ad45fb58e8d0039006/pkg/ingester/stream.go#L72

**Comment by akvlad** [comment]
https://github.com/grafana/loki/blob/a3bacd5739da2d41f3f9a2ad45fb58e8d0039006/vendor/github.com/prometheus/common/model/fingerprinting.go#L23
@derlaft sorry, but we can't just replace the fingerprinting function due to backward compatibility reasons.. I'll discuss with @lmangani if we will make a env config for this or make the the fingerprint function pluggable.

**Comment by derlaft** [comment]
> https://github.com/grafana/loki/blob/a3bacd5739da2d41f3f9a2ad45fb58e8d0039006/vendor/github.com/prometheus/common/model/fingerprinting.go#L23

`FNV-1A` should still be much better than what's currently used btw

> sorry, but we can't just replace the fingerprinting function due to backward compatibility reasons..

What exactly will break? From my understanding, new entries will use new fingerprint values, and in query time they will be joined into the result anyways. Maybe I am missing something.

> if we will make a env config for this or make the the fingerprint function pluggable.

This is a major problem, IMO it has to be solved out of box one way or another (mapping hash values and avoiding collisions like in cloki).

**Comment by derlaft** [comment]
There's another minor problem. 

Here value is converted from int to hex: https://github.com/lmangani/cLoki/blob/c40d1d9664523e60964a8d0b9338575c0a6d4720/lib/utils.js#L25

Here value is converted from hex to int again: https://github.com/joakimbeng/short-hash/blob/b7e1178b45b06bbf1697ba428b7da53664e96979/src/index.js#L5

**Comment by derlaft** [comment]
> This is a major problem, IMO it has to be solved out of box one way or another 

So currently in the cloki install I observe only 752 label combinations (`select uniq(arraySort(JSONExtractKeysAndValuesRaw(labels))) from time_series`) (total rows: 3196510), but whole 185 different collisions (`select count() from (select fingerprint, uniq(arraySort(JSONExtractKeysAndValuesRaw(labels))) c from time_series group by fingerprint having c > 1)
`)

**Comment by derlaft** [comment]
Interesting: despite having `UInt64` in database schema, it looks like current hash function produces 32-bit value:

```
> shortHash('wutwutwutwutwutwutwutwutwut')
'6710f373'
```

```
SELECT max(fingerprint)
FROM samples_v2

┌─max(fingerprint)─┐
│       4294963361 │
└──────────────────┘
```

**Comment by akvlad** [comment]
@derlaft https://github.com/lmangani/cLoki/pull/115 
This should satisfy everyone's needs.

**Comment by lmangani** [comment]
@akvlad thanks Vlad once again for leading this change
@derlaft changes were merged to master and CI builders should produce the containers shortly. Please let us know if this resolves this thread, and please feel free to PR any other suggestion you might have to the code anytime!

**Comment by akvlad** [comment]
Yes. 
What about samples and samples_v2? 
how many entries do you have in `the samples` table? What is the last timestamp in the `samples` table?

**Comment by derlaft** [comment]
```
SELECT
    count(),
    max(timestamp_ms)
FROM samples_v2

┌──count()─┬─max(timestamp_ms)─┐
│ 26488160 │     1644506160881 │
└──────────┴───────────────────┘
```

**Comment by derlaft** [comment]
Yes!

`FROM cloki.samples_v2` does not OOM

**Comment by derlaft** [comment]
I think this one can be closed now
