### ISSUE TITLE
Use DateTime64 type for store time

### ISSUE THREAD

**Issue by R-omk** [lmangani/cLoki#120]
When at one moment it writes several lines of logs, then the accuracy in ms is not enough. In this case, the order of the lines may be violated.

The screenshot shows that the initial precision that the containerd provides is much more accurate, which allows you to maintain the order of the lines.

![image](https://user-images.githubusercontent.com/1633879/153901941-199e90c5-5d23-46cc-b60b-c8fa4b77304e.png)

**Comment by lmangani** [comment]
Planned for v3 format increasing the internal time resolution and adding compression. Updates will follow.

**Comment by lmangani** [comment]
Please test the latest releases and let us know your feedback

**Comment by R-omk** [comment]
In the new version, sorting works as it should. I guess we can close this issue

**Comment by lmangani** [comment]
THanks @R-omk and totally up to your satisfaction. We want to push every limit so input and criticism to optimize are always welcome!
