### ISSUE TITLE
Same labels produce different fingerprints

### ISSUE THREAD

**Issue by derlaft** [lmangani/cLoki#134]
Hi,

we are running `cLoki` with `HASH=xxhash64`

and recently started receiving OOMs even on the most simple queries (5-minute ranges, for example).

It looks like there's something unhealthy going on with fingerprint duplication:

```
select
    uniq(fingerprint),
    uniq(arraySort(JSONExtractKeysAndValuesRaw(labels)))
from time_series
WHERE (JSONHas(labels, 'pod_namespace') = 1) AND (JSONExtractString(labels, 'pod_namespace') = '***')

┌─uniq(fingerprint)─┬─uniq(arraySort(JSONExtractKeysAndValuesRaw(labels)))─┐
│            556429 │                                                   32 │
└───────────────────┴──────────────────────────────────────────────────────┘
```

Same label sets keep producing vastly different fingerprints for some reasons now. Do you have any idea why it could happen?

**Comment by derlaft** [comment]
I've selected a very specific label set and here are the results:

```
SELECT
    uniq(arraySort(JSONExtractKeysAndValuesRaw(labels))),
    uniq(fingerprint)
FROM time_series
WHERE ((JSONHas(labels, 'pod_namespace') = 1) AND (JSONExtractString(labels, 'pod_namespace') = '***')) AND ((JSONHas(labels, 'app_id') = 1) AND (JSONExtractString(labels, 'app_id') = '4')) AND ((JSONHas(labels, 'container_image') = 1) AND (JSONExtractString(labels, 'container_image') = '***')) AND ((JSONHas(labels, 'container_name') = 1) AND (JSONExtractString(labels, 'container_name') = '***')) AND ((JSONHas(labels, 'event_type') = 1) AND (JSONExtractString(labels, 'event_type') = '***')) AND ((JSONHas(labels, 'level') = 1) AND (JSONExtractString(labels, 'level') = 'debug')) AND ((JSONHas(labels, 'pod_node_name') = 1) AND (JSONExtractString(labels, 'pod_node_name') = '***')) AND ((JSONHas(labels, 'stream') = 1) AND (JSONExtractString(labels, 'stream') = 'stderr'))

Query id: 87733e06-ef86-4c20-98b6-68e79c9d6aff

┌─uniq(arraySort(JSONExtractKeysAndValuesRaw(labels)))─┬─uniq(fingerprint)─┐
│                                                    1 │             38957 │
└──────────────────────────────────────────────────────┴───────────────────┘
```

**Comment by akvlad** [comment]
@derlaft can you estimate 
`SELECT count(1) from time_series`
`SELECT count(1) from time_series WHERE (JSONHas(labels, 'pod_namespace') = 1) AND (JSONExtractString(labels, 'pod_namespace') = '***')`
?

**Comment by derlaft** [comment]
@akvlad 

`count() from time_series`: `7007130`
`count() from time_series` with one label filter: `3758921`
`count() from time_series` [for one specific label combination](https://github.com/lmangani/cLoki/issues/134#issuecomment-1077546252): `159589`

**Comment by akvlad** [comment]
@derlaft do you have OOM for the 159K response as well?

**Comment by derlaft** [comment]
@akvlad no

**Comment by akvlad** [comment]
@derlaft so for the 3M select only. I'll generate similar amount of fingerprints and try to make some optimizations.

**Comment by derlaft** [comment]
@akvlad I don't think the problem is the amount of rows. I think the problems is that it for some reasons generates different fingerprints for same labels. In this setup we hardly have enough different label combinations to justify 3M rows and 10G of RAM used

**Comment by derlaft** [comment]
```
SELECT
    count(),
    uniq(fingerprint),
    uniq(arraySort(JSONExtractKeysAndValuesRaw(labels)))
FROM time_series

Query id: 34c2384c-b5a2-4196-8f65-bab9e230c10a

┌─count()─┬─uniq(fingerprint)─┬─uniq(arraySort(JSONExtractKeysAndValuesRaw(labels)))─┐
│ 7026589 │           2981955 │                                                  333 │
└─────────┴───────────────────┴──────────────────────────────────────────────────────┘

```

There's only 333 uniq label combination in the system. I don't having 3M uniq fingerprints and 7M rows is expected for such a small dataset.

**Comment by akvlad** [comment]
@derlaft we have a solution candidate for your problem.
https://github.com/lmangani/cLoki/tree/labels_oom
1. it should stabilize fingerprints.
2. it should avoid OOM for **raw logs requests** time series requests can't be tuned this way. 
Feel free to check

**Comment by akvlad** [comment]
Hello @derlaft.
One more update for the OOM problem. Please check if the latest version in the https://github.com/lmangani/cLoki/tree/labels_oom branch doesn't fail with OOM.

**Comment by akvlad** [comment]
@derlaft  It's more interesting if the request for the last week (you remember 3M fingerprints) fails now or not. Can you try `{pod_namespace="***"}` for a long period?
