### ISSUE TITLE
Log/Table rotation in cLoki

### ISSUE THREAD

**Issue by MohammadrezaNasrabadi** [lmangani/cLoki#154]
Hello

I'm using cLoki and in my use case I want the logs stored in clickhouse should be rotated and removed by weekly, monthly or ...
Just like logrotate tool that do such this action for syslog files.

I find two environment variables that their description is close to such this action: `LABELS_DAYS` and `SAMPLES_DAYS`
Is these variables really do table rotation in clickhouse?

**Comment by MohammadrezaNasrabadi** [comment]
> Hello @MohammadrezaNasrabadi Yes, that's correct. The data in cLoki is automatically rotated by TTL on inserts, so each write contains the expiration matching the _DAYS settings for either samples or labels. If this is not granular enough, you most definitely can perform tailored removals since everything is timestamped, its is extremely easy to create custom rotations or drops based on data age or tags directly using ClickHouse. I hope this helps!

Thanks a lot for your help dear @lmangani

**Comment by lmangani** [comment]
No problem and welcome to our community @MohammadrezaNasrabadi - Any feedback is super useful and appreciated!

**Comment by KleinenberG** [comment]
Hello @lmangani .Please, can i get deatais about rotation variables?
I setup both variables
```
      LABELS_DAYS: 7,
      SAMPLES_DAYS: 7,
```
but I see files older than 7 days

```
drwxr-x--- 2 systemd-resolve systemd-journal 4096 Dec 14 12:46 202212_657575_657819_57
drwxr-x--- 2 systemd-resolve systemd-journal 4096 Dec 14 12:16 202212_656880_657574_159
drwxr-x--- 2 systemd-resolve systemd-journal 4096 Dec 14 10:49 202212_655946_656879_166
drwxr-x--- 2 systemd-resolve systemd-journal 4096 Dec 14 09:01 202212_599395_655945_168
drwxr-x--- 2 systemd-resolve systemd-journal 4096 Dec  9 12:17 202212_540183_599394_173
drwxr-x--- 2 systemd-resolve systemd-journal 4096 Dec  5 17:29 202211_500841_503460_99
drwxr-x--- 2 systemd-resolve systemd-journal 4096 Dec  4 08:07 202212_503465_540182_167
drwxr-x--- 2 systemd-resolve systemd-journal 4096 Dec  1 03:15 202211_503461_503464_1
drwxr-x--- 2 systemd-resolve systemd-journal 4096 Nov 30 21:32 202211_497919_500840_162
drwxr-x--- 2 systemd-resolve systemd-journal 4096 Nov 30 15:33 202211_482366_497918_162
drwxr-x--- 2 systemd-resolve systemd-journal 4096 Nov 29 17:04 202210_1_158056_206
drwxr-x--- 2 systemd-resolve systemd-journal 4096 Nov 29 08:58 202211_420098_482365_177
drwxr-x--- 2 systemd-resolve systemd-journal 4096 Nov 27 10:22 202211_158057_331915_211
drwxr-x--- 2 systemd-resolve systemd-journal 4096 Nov 23 23:33 202211_331916_420097_192
drwxr-x--- 2 systemd-resolve systemd-journal 4096 Oct 18 09:34 detached
-rw-r----- 1 systemd-resolve systemd-journal    1 Oct 18 09:34 format_version.txt
```

**Comment by lmangani** [comment]
Hello @KleinenberG 
We would need to see this data from clickhouse as the folders are not particularly indicative. 
What's the oldest record you can select from the qryn tables?

**Comment by lmangani** [comment]
PS: @KleinenberG please open a new issue if needed.
