### ISSUE TITLE
GO Port

### ISSUE THREAD

**Issue by lmangani** [lmangani/cLoki#17]
We are actively porting cLoki to golang for performance and consolidation of features and to reach its full potential with Clickhouse. If you' d like to be part of this initiative as developer, designer or tester, please +1 or post a comment to this issue.

Thanks in advance!

**Comment by Slach** [comment]
really interesting initiative
I can test it and may make performance test

**Comment by lmangani** [comment]
Thanks @Slach so much appreciated! Performance is key to this project, so we can sure use help there!

Will post updates to this thread periodically so watch this issue.

**Comment by lmangani** [comment]
For anyone interested, the first version has been released for testing and feedback: https://github.com/qxip/cloki-go

**Comment by Slach** [comment]
wow ;) glad to see progress ;) guys thanks a lot for your efforts
