### ISSUE TITLE
Is /loki/api/v1/push Schema different from Loki on purpose?

### ISSUE THREAD

**Issue by shawel** [lmangani/cLoki#24]
I get this from Loki API doc https://grafana.com/docs/loki/latest/api/#post-lokiapiv1push
```

{
  "streams": [
    {
      "stream": {
        "label": "value"
      },
      "values": [
          [ "<unix epoch in nanoseconds>", "<log line>" ],
          [ "<unix epoch in nanoseconds>", "<log line>" ]
      ]
    }
  ]
}
```

**Comment by lmangani** [comment]
Hey @shawel thanks for bringing this up. are you referring to the readme or the code?

**Comment by shawel** [comment]
Thanks for the reply @shawel 

I don't think insert will be successful for the above push API.  It works for the following format but this is really different from what is documented on Loki Website
 `{"labels":"{\"__name__\":\"up\"}","entries":[{"timestamp":"2018-12-26T16:00:06.944Z","line":"zzz"}]}`

Most specifically it fails on https://github.com/lmangani/cLoki/blob/122c81cdabd211a53cad1a05a35814d5f96ec9b2/cloki.js#L143  because it is not finding labels object.

**Comment by lmangani** [comment]
I believe that's the pre-v1 api format

**Comment by lmangani** [comment]
I checked and indeed, this is the old Loki v0 API push format right there. We've focused on the query APIs so far but it's a simple patch luckily.

**Comment by shawel** [comment]
ok! thanks! Just starting to test it out and wasn't sure

**Comment by lmangani** [comment]
@shawel pushed a new block to handle the format when there are `values` rather than `entries`

**Comment by shawel** [comment]
Ok! perfect thank you @lmangani. I will test and close

**Comment by shawel** [comment]
HI @lmangani  The code change failed to work for me. I think there were several places that did not conform to the schema.

I think this should be stream.stream https://github.com/lmangani/cLoki/blob/57eefc92100e3d7a3f9b23ec887c16d14ce20319/cloki.js#L168

stream.labels no longer exists in the schema 
https://github.com/lmangani/cLoki/blob/57eefc92100e3d7a3f9b23ec887c16d14ce20319/cloki.js#L149

stream.values bulk add fails to insert because it is expecting  a UInt64 but getting whole values object 
https://github.com/lmangani/cLoki/blob/57eefc92100e3d7a3f9b23ec887c16d14ce20319/cloki.js#L184



Something like this worked for me
```
if (streams) {
		console.log(JSON.stringify(req.body));
		streams.forEach(function (stream) {
			try {
				try {
					var JSON_labels;
					if (stream.stream) {
						JSON_labels = stream.stream;
					} else {
						JSON_labels = toJSON(
							stream.labels.replace(/\!?="/g, ':"')
						);
					}
				} catch (e) {
					console.error(e);
					return;
				}
				// Calculate Fingerprint
				var finger = fingerPrint(JSON.stringify(JSON_labels));
				if (debug)
					console.log("LABELS FINGERPRINT", stream.labels, finger);
				labels.add(finger, stream.labels);
				// Store Fingerprint
				bulk_labels.add(finger, [
					new Date().toISOString().split("T")[0],
					finger,
					JSON.stringify(JSON_labels),
					JSON_labels["name"] || "",
				]);
				for (var key in JSON_labels) {
					if (debug)
						console.log("Storing label", key, JSON_labels[key]);
					labels.add("_LABELS_", key);
					labels.add(key, JSON_labels[key]);
				}
			} catch (e) {
				console.log(e);
			}

			if (stream.entries) {
				stream.entries.forEach(function (entry) {
					if (debug) console.log("BULK ROW", entry, finger);
					if (
						!entry &&
						(!entry.timestamp || !entry.ts) &&
						(!entry.value || !entry.line)
					) {
						console.error("no bulkable data", entry);
						return;
					}
					var values = [
						finger,
						new Date(entry.timestamp || entry.ts).getTime(),
						entry.value || 0,
						entry.line || "",
					];
					console.log(values);
					bulk.add(finger, values);
				});
			}

			if (stream.values) {
				stream.values.forEach(function (value) {
					if (debug) console.log("BULK ROW", value, finger);
					if (!value && !value[0] && !value[1]) {
						console.error("no bulkable data", value);
						return;
					}
					var values = [
						finger,
						Math.round(value[0] / 1000000), // convert to millieseconds
						0,
						value[1],
					];
					bulk.add(finger, values);
				});
			}
		});
	}
```

**Comment by lmangani** [comment]
Great, thanks for sharing this! could you send a PR with your changes?

**Comment by shawel** [comment]
sure thing!
