### ISSUE TITLE
imagestore

### ISSUE THREAD

**Issue by lmangani** [lmangani/cloki#3]
![ezgif com-optimize 15](https://user-images.githubusercontent.com/1423657/50496835-404e6480-0a33-11e9-87a4-aebb71a668a7.gif)

**Comment by lmangani** [comment]
![image](https://user-images.githubusercontent.com/1423657/54091852-5ce91000-4385-11e9-849d-998c1e5d3243.png)

**Comment by lmangani** [comment]
![image](https://user-images.githubusercontent.com/1423657/58560408-5a2fe580-8225-11e9-8198-22f84033989b.png)

**Comment by lmangani** [comment]
![ezgif com-gif-maker](https://user-images.githubusercontent.com/1423657/99530591-d0885080-29a1-11eb-87e6-870a046fb4de.gif)

**Comment by lmangani** [comment]
![cloki_logo](https://user-images.githubusercontent.com/1423657/99822833-f9504780-2b53-11eb-8b28-99484eab6157.png)

**Comment by Slach** [comment]
nice logo ;)

**Comment by lmangani** [comment]
![image](https://user-images.githubusercontent.com/1423657/104443022-26d6d180-5596-11eb-907a-9925a43e9a32.png)

**Comment by lmangani** [comment]
![image](https://user-images.githubusercontent.com/1423657/135249640-5f5a61e5-0f94-4517-b052-76d47c3572f5.png)

**Comment by lmangani** [comment]
LIVE MODE
![ezgif com-gif-maker](https://user-images.githubusercontent.com/1423657/140958818-cb91c574-01ed-4792-ba41-747e31dbc30f.gif)

**Comment by Dletta** [comment]
<img width="1526" alt="Screen Shot 2021-11-11 at 3 43 07 PM" src="https://user-images.githubusercontent.com/5729042/141498186-6a08b398-55f7-40dd-9a57-6010cda3dece.png">

**Comment by lmangani** [comment]
![ezgif com-gif-maker (31)](https://user-images.githubusercontent.com/1423657/143876342-85531041-aca5-4892-a218-e8775674867d.gif)

**Comment by lmangani** [comment]
![image](https://user-images.githubusercontent.com/1423657/146674326-302bde15-4e65-48a6-a824-6c1f5ea04a63.png)

**Comment by lmangani** [comment]
![cloki-udf](https://user-images.githubusercontent.com/1423657/146674780-0b2b4431-c550-498d-beae-ad7c7f3ce3c5.png)

**Comment by lmangani** [comment]
![image](https://user-images.githubusercontent.com/1423657/147671576-d4a21814-e2bf-46a6-bfb3-99489d92658c.png)

**Comment by Dletta** [comment]
<img width="798" alt="Screen Shot 2021-12-29 at 9 32 50 AM" src="https://user-images.githubusercontent.com/5729042/147678155-75b8c6ee-1c65-4da8-b36f-b047cb3abffb.png">

**Comment by Dletta** [comment]
<img width="1347" alt="Screen Shot 2021-12-29 at 9 34 53 AM" src="https://user-images.githubusercontent.com/5729042/147678331-b10c11f2-1595-4d0d-94c9-5d4a1efd6d12.png">

**Comment by Dletta** [comment]
<img width="760" alt="Screen Shot 2021-12-29 at 9 37 59 AM" src="https://user-images.githubusercontent.com/5729042/147678693-80d40b1a-fd15-40bf-8c37-ccc9ac787bc1.png">

**Comment by Dletta** [comment]
<img width="1419" alt="Screen Shot 2021-12-29 at 10 21 08 AM" src="https://user-images.githubusercontent.com/5729042/147682851-81b8146a-5776-4cc0-8e38-b4295dd57769.png">

**Comment by lmangani** [comment]
![image](https://user-images.githubusercontent.com/1423657/147689245-8ebe63af-da25-4ffa-9748-f78d1337357c.png)

**Comment by lmangani** [comment]
![image](https://user-images.githubusercontent.com/1423657/147824177-2ace7bf5-c40e-429b-a81d-0be0b28e7bb7.png)

**Comment by lmangani** [comment]
![image](https://user-images.githubusercontent.com/1423657/147888567-698fbe2c-e4e0-47df-aec8-a1fc40b04194.png)

**Comment by lmangani** [comment]
![image](https://user-images.githubusercontent.com/1423657/148109045-62d70a11-58e7-4fc4-a72a-538749baca9e.png)

**Comment by lmangani** [comment]
![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/1423657/165121183-1d68415e-d39c-4bbc-b478-3cd65bfd0ab6.gif)

**Comment by lmangani** [comment]
![ezgif com-gif-maker (4)](https://user-images.githubusercontent.com/1423657/166163222-9878936e-5114-4ece-883f-f721f5fba8ee.gif)

![ezgif com-gif-maker (5)](https://user-images.githubusercontent.com/1423657/166163594-c51cc598-50a2-4136-8792-91b45024c8d9.gif)

**Comment by lmangani** [comment]
![image](https://user-images.githubusercontent.com/1423657/167260809-6a61647e-32ad-4820-834b-5771f372c7f3.png)

**Comment by lmangani** [comment]
![image](https://user-images.githubusercontent.com/1423657/168768437-9975ae5e-233b-49ac-9b3a-a9b127abab38.png)

**Comment by lmangani** [comment]
Uptrace + cLoki
![image](https://user-images.githubusercontent.com/1423657/171365866-d4de702e-cafe-4289-bb5e-47e0e32bf8ee.png)
![image](https://user-images.githubusercontent.com/1423657/171365914-a9524f9c-c35b-48c4-9903-9ddca9c16d85.png)

**Comment by lmangani** [comment]
![image](https://user-images.githubusercontent.com/1423657/173138081-7fdc631c-eeff-4fb0-b9a5-b1cb18567b92.png)

**Comment by lmangani** [comment]
![image](https://user-images.githubusercontent.com/1423657/173144443-fc7ba783-d5bf-47f9-bf59-707693da5ed1.png)

**Comment by lmangani** [comment]
![image](https://user-images.githubusercontent.com/1423657/182460248-0f82c0a2-ee52-41f6-b2c0-8af624aba93f.png)

**Comment by lmangani** [comment]
![image](https://user-images.githubusercontent.com/1423657/182460396-24f84692-0e77-491c-af54-7c76a149e50a.png)

**Comment by lmangani** [comment]
![image](https://user-images.githubusercontent.com/1423657/189417653-d4de5282-1320-45dd-9466-45d95237b534.png)

**Comment by lmangani** [comment]
![ezgif com-gif-maker (11)](https://user-images.githubusercontent.com/1423657/196654073-b84a218c-6a70-49bb-a477-e8be5714e0ba.gif)
![ezgif com-gif-maker (12)](https://user-images.githubusercontent.com/1423657/196654084-1f1d8a62-3fd2-4420-a2fa-57ac2872938c.gif)
![ezgif com-gif-maker (13)](https://user-images.githubusercontent.com/1423657/196654097-8a235253-bf5d-4937-9e78-fddf12819d44.gif)

**Comment by lmangani** [comment]
![view-demo-all](https://user-images.githubusercontent.com/1423657/198894517-79c58f75-6108-4a07-99a2-3a41ca833fc8.png)
![view-demo-flux](https://user-images.githubusercontent.com/1423657/198894519-d34e1ee0-8a52-4e5a-bb2f-0a8c48360d07.png)
![view-demo-promqlmetrics](https://user-images.githubusercontent.com/1423657/198894520-4294be9e-45a3-4308-8e27-7c789f5a218b.png)
![view-demo-logqlmetrics](https://user-images.githubusercontent.com/1423657/198894521-3beb28d2-4051-425f-899c-892a13130d2b.png)
![view-demo-logs](https://user-images.githubusercontent.com/1423657/198894522-9b6f5cd5-8115-45ae-8fe9-c31df56f5665.png)

**Comment by lmangani** [comment]
![q_cloud_bubble](https://user-images.githubusercontent.com/1423657/200818512-484cd226-87ae-47c4-8431-20f5a3cdca2c.png)

![image](https://user-images.githubusercontent.com/1423657/200818709-4ed3d946-9210-4d82-8a57-42d88d27d4dc.png)

**Comment by lmangani** [comment]
![qryn_3d_project_glow](https://user-images.githubusercontent.com/1423657/201530880-ed3358f7-1be4-449b-b21e-03f86eebf06a.png)

**Comment by lmangani** [comment]
![image](https://user-images.githubusercontent.com/1423657/215276389-4d670a0b-2ea4-4bdf-9650-6f017ef759f5.png)

**Comment by lmangani** [comment]
![image](https://user-images.githubusercontent.com/1423657/217843906-b4637220-a420-4ad6-a7e9-3cb874c79e3b.png)

**Comment by lmangani** [comment]
![QRYN CLOUD LOGO](https://user-images.githubusercontent.com/1423657/218816262-e0e8d7ad-44d0-4a7d-9497-0d383ed78b83.png)
