### ISSUE TITLE
cLoki - Live Update Mode

### ISSUE THREAD

**Issue by Dletta** [lmangani/cLoki#30]
## Problem

Live Update Mode is not yet implemented.

## Goal / Solution / Example 

Query: {type="call"}

* Grafana expects a websocket to be opened based on the query path below
 * ws://grafana/api/datasources/proxy/24/loki/api/v1/tail?query=%7Btype%3D%22call%22%7D 
* The data that comes back from Loki (one line, but here prettified for reading 
 * ```JSON
    { 
     "streams": [
       {
        "stream": {
         "duration":"0",
         "from_user":"311",
         "ruri_user":"00048177783344",
         "status":"8",
         "type":"call"
        },
     "values":[
       [
        "1631983284788000000",
        "USER_FAILURE 0 seconds call with 22177e4b-b394-4c54-8250-8ce5563d5c8b from 311@136.243.16.181 (193.46.255.223:47385) to 00048177783344@ (136.243.16.181:5060)"
       ]
      ]
     }
    ]
   }
```

Seems it is not much different in response as a normal query results, minus the 'overhead' or 'meta data' that we receive on the first answer. In the back Grafana gets the 'existing' data via http response and then opens the websocket for future update. (Seems like it sets up a watcher on backend (well of course how else))

**Comment by akvlad** [comment]
Done with the PR.
