### ISSUE TITLE
`/api/v1/query` API not working?

### ISSUE THREAD

**Issue by navinpai** [lmangani/cLoki#64]
Been following [some of the documentation in the wiki](https://github.com/lmangani/cLoki/wiki/HTTP-API#cloki-http-api) and unsure why the `/api/v1/query` API does not return any results.

### How To Repro
```
$ curl -i -XPOST -H "Content-Type: application/json" http://localhost:3100/loki/api/v1/push --data '{"streams":[{"labels":"{\"__name__\":\"up\"}","entries":[{"timestamp":"2018-12-26T16:00:06.944Z","line":"zzz"}]}]}'
HTTP/1.1 200 OK
```

```
 $ curl "http://localhost:3100/loki/api/v1/labels"
{"status":"success","data":["filename","job","__name__"]
```

```
$ curl "http://localhost:3100/loki/api/v1/label/__name__/values"
{"status":"success","data":["up"]}
``` 
PS This API in the wiki is incorrect, it says `api/v1/__name__` instead of `api/v1/label/__name__`

```
$ curl "http://localhost:3100/loki/api/v1/query?query='{__name__="up"}'"
{"status":"success","data":{"resultType":"streams","result":[]}}
```

---
If I set `DEBUG=true` , I see this in the logs:
```
GET /loki/api/v1/query
QUERY:  [Object: null prototype] { query: "'__name__=up'" }
LABEL undefined VALUES []
```

The issue seems to be https://github.com/lmangani/cLoki/blob/master/lib/handlers/query.js#L8 where `query.name` is undefined. 

Am I doing something wrong here?

**Comment by lmangani** [comment]
Hello @navinpai 

Thanks for your report! There are indeed "leftovers" of the Loki 1.0 API here and there, and documentation for manual actions might need refresh. We'll make sure the examples for the `query` API are rectified in the coming days.

Now, `query` is used for doing queries against a single point in time, while most of the focus is on the Grafana integration at this time where `query_range` is the core function:

Here's a working example:
```
curl -G -s localhost:3100/loki/api/v1/query_range --data-urlencode 'query={type="clickhouse"}'
```

**Comment by lmangani** [comment]
Patches for `/query` endpoint being worked in https://github.com/lmangani/cLoki/pull/65

**Comment by navinpai** [comment]
Thanks for the quick reply @lmangani 

Unfortunately, looks like `query_range` is not working for me either.

### How to Reproduce

node v.17.0.1
cloki (current master: f3b32b5588942d888bbf0b55b8999904b9fddda0)
clickhouse v 21.12.1.8808

```
# Run Cloki to create initial tables in empty test db
DEBUG="true" CLICKHOUSE_SERVER="127.0.0.1" CLICKHOUSE_AUTH="default:" CLICKHOUSE_DB="test" node ./cloki.js

# Push log
$ curl -i -XPOST -H "Content-Type: application/json" http://localhost:3100/loki/api/v1/push --data '{"streams":[{"labels":"{\"__name__\":\"metric\"}","entries":[{"timestamp":"2021-11-21T16:00:06.944Z","value":"100"}]}]}'
HTTP/1.1 200 OK

# Ensure label is present
$ curl localhost:3100/loki/api/v1/label/__name__/values
{"status":"success","data":["metric"]}

# Query for data
curl -G -s localhost:3100/loki/api/v1/query_range --data-urlencode 'query={__name__="metric"}'
{"status":"success", "data":{ "resultType":"streams", "result": []}}
```
Debug logs show:
```
GET /loki/api/v1/query_range
QUERY:  [Object: null prototype] { query: '{__name__="metric"}' }
Scanning Fingerprints...
Scanning Fingerprints...
```

and I also see the data in clickhouse in `time_series` table and the `samples_read` table:
```
┌───────date─┬─fingerprint─┬─labels────────────────┬─name─┐
│ 2021-11-21 │  1417368218 │ {"__name__":"metric"} │      │
└────────────┴─────────────┴───────────────────────┴──────┘

┌─fingerprint─┬──timestamp_ms─┬─value─┬─string─┐
│  1417368218 │ 1637510406944 │   100 │        │
└─────────────┴───────────────┴───────┴────────┘
```

Any idea what I may be missing here?

**Comment by lmangani** [comment]
Thanks for the details, I see the issue now - the example is a bit misleading and it seems you're inserting metrics rather than strings/logs. This is a special feature for timeseries. You should insert to the line column instead as clients do.

```
curl -i -XPOST -H "Content-Type: application/json" http://localhost:3100/loki/api/v1/push --data '{"streams":[{"labels":"{\"__name__\":\"up\"}","entries":[{"timestamp":"2020-11-21T21:00:09.999Z","line":"zzz"}]}]}'
```

Things should work if you push lines (please confirm)
 
More importantly everything works as intended when using Loki clients and Grafana which is our intended usecase.

**Comment by lmangani** [comment]
Unrelated note: only node 14.x and 16.x are officially supported and other version might fail.

**Comment by navinpai** [comment]
> You should insert to the line column instead as clients do.

Ah yes... that seems to have fixed it. 

> More importantly everything works as intended when using Loki clients and Grafana which is our intended usecase.

The usecase I'm playing with cloki for is quite similar but I'm a suckler for testing APIs directly to know what's flowing in and out! 😄. I also confirmed via grafana that the data being pushed manually via is being returned there! Would be nice to have some simple examples to have people up and running, but can close this out for now! 👍 

Thanks again @lmangani !

**Comment by lmangani** [comment]
We'll extend the documentation with better examples. Thanks for taking the time to confirm & welcome to our users family!
