### ISSUE TITLE
Configurable Payload Size

### ISSUE THREAD

**Issue by mr-karan** [lmangani/cLoki#69]
I'm using https://vector.dev/ to push logs to `cLoki`. I've configured the batch size as 1MiB, because the log volume is huge (225GB file), so I want fewer requests to upstream (cLoki and subsequently even Clickhouse). Batching multiple log lines is ideal way to do it.

However, I am getting an error from `cLoki`:

```
{ status: 413, version: HTTP/1.1, headers: {"content-type": "application/json; charset=utf-8", "content-length": "120", "date": "Mon, 29 Nov 2021 11:42:16 GMT", "connection": "keep-alive", "keep-alive": "timeout=5"}, body: b"{\"statusCode\":413,\"code\":\"FST_ERR_CTP_BODY_TOO_LARGE\",\"error\":\"Payload Too Large\",\"message\":\"Request body is too large\"}" }
```

Looks like the default payload size is 1MB. I couldn't find how to tweak this parameter: https://www.fastify.io/docs/latest/Server/#bodylimit. Maybe we should make it configurable via ENV vars?

Thanks

**Comment by lmangani** [comment]
Thanks for the report @mr-karan 

This seems indeed an excellent idea - could you try to [hotpatch your local cloki.js](https://github.com/lmangani/cLoki/blob/master/cloki.js#L47)  with a custom bodyLimit value to confirm if this alone works?

```
/* Fastify Helper */
const fastify = require('fastify')({
  logger: false,
  bodyLimit: process.env.FASTIFY_BODYLIMIT || 1048576
})
```

**Comment by mr-karan** [comment]
That fixes it, thanks for the prompt reply. Just a minor correction, we need to ensure the value is `int` for the env variable:

```
/* Fastify Helper */
const fastify = require('fastify')({
  logger: false,
  bodyLimit: parseInt(process.env.FASTIFY_BODYLIMIT) || 1048576
})
```

**Comment by lmangani** [comment]
That's great! Thanks @mr-karan 
Before adding this in a PR, do you foresee any other fastify parameters being generally useful other than `bodyLimit`?

**Comment by mr-karan** [comment]
Looked at the docs and I can only think of setting up a sane default value for https://www.fastify.io/docs/latest/Server/#requesttimeout (Default is no timeout, seems like a bad idea honestly as it's easy to DoS)

**Comment by lmangani** [comment]
Done!
```
| FASTIFY_BODYLIMIT | 5242880   | API Maximum payload size in bytes |
| FASTIFY_REQUESTTIMEOUT | 0 | API Maximum Request Timeout in ms |
| FASTIFY_MAXREQUESTS | 0 | API Maximum Requests per socket |
```

**Comment by mr-karan** [comment]
Awesome, thanks!

**Comment by lmangani** [comment]
published cloki@1.1.16

Thanks for your help!

**Comment by lmangani** [comment]
@mr-karan could you perhaps share a vector/cloki configuration example for the wiki?

**Comment by mr-karan** [comment]
Sure. Here's a `vector.toml` sample file:

```
# Set global options
data_dir = "/var/lib/vector"

# Vector's API (disabled by default)
# Enable and try it out with the `vector top` command
[api]
enabled = true

# Ingest data by tailing one or more files
[sources.nginx_logs]
type         = "file"
include      = ["/var/log/nginx/*.log"]       # supports globbing
ignore_older = 86400                          # 1 day

# Structure and parse via Vector's Remap Language
[transforms.nginx_parser]
inputs = ["nginx_logs"]
type   = "remap"
source = '''
. = parse_nginx_log(.message)
'''

[sinks.loki]
type = "loki"
inputs = ["nginx_parser"]
endpoint = "http://127.0.0.1:3100"
encoding.codec = "json"
encoding.timestamp_format = "rfc3339"
healthcheck.enabled = true
# Add labels to identify a log stream.
labels.hostname = "{{ client }}"
labels.job = "vector"
labels.source = "/var/log/nginx"
# Remove fields that have been converted to labels to avoid having them twice.
remove_label_fields = true
out_of_order_action="rewrite_timestamp"
remove_timestamp=true
batch.max_bytes = 1049000 # 1MB
batch.timeout_secs = 5
buffer.max_size = 104900000 #104.9MB
buffer.type = "disk"
buffer.when_full = "block"
```

The `docker-compose` part for `cLoki` is pretty standard, no extra config needed:

```
  cloki:
    image: mrkaran/cloki:latest
    container_name: loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    environment:
      - CLICKHOUSE_SERVER=clickhouse-seed
      - DEBUG=false
      - FASTIFY_BODYLIMIT=10485760
    depends_on:
      - clickhouse-seed
    labels:
      org.label-schema.group: "monitoring"
```
