### ISSUE TITLE
Benchmark Performance

### ISSUE THREAD

**Issue by lmangani** [lmangani/cLoki#7]
We would like to benchmark the current (and potential) performance of cLoki to find and eliminate any bottlenecks on its way to Clickhouse. 

If anyone is willing to help or lead this effort, please attach to this issue :)

**Comment by akvlad** [comment]
I'd like to ask about the current state of the issue.
Do you already have a training database to test and benchmark?

**Comment by lmangani** [comment]
Hey @akvlad no state really - never made it very far on my own other than basic testing of basic tag queries against the original Loki API with fake datasets during development where cloki was only a couple milliseconds behind according on the Grafana measurements in read - never tested the inserting part as I mostly intended this as a query/read gateway.

I guess this would ultimately become a clickhouse benchmark + cLoki API benchmark, with the node app being clearly where we expected the most bottlenecks in performance (reason for starting the cloki-go port)

Do you have any ideas or suggestions?

**Comment by akvlad** [comment]
Well. As far as I need some data to test the logql parser, I stopped to create some sample log generators. 
They are here:
https://github.com/akvlad/cLoki/blob/integration_test_benchmarks/test/insert.benchmark.test.js
I can try doing a PR. Or I can merge these into the main cLoki. I'm not sure about the rules of the society.

**Comment by lmangani** [comment]
Make yourself home! I invited you to join the repository, just visit the home to accept. Feel free to make branches and PRs. If you'd like we can arrange a session sometime soon to discuss ideas.

**Comment by akvlad** [comment]
I'm very sorry, I've overslept the invitation. Can I get another one please?
Yes. We can arrange a session. Next Saturday maybe? I'm free in weekends.

**Comment by lmangani** [comment]
Refreshed the invite

**Comment by lmangani** [comment]
Thanks for accepting and for your enthusiasm! Let's coordinate for next weekend will try find a way to contact you directly ;)
