### ISSUE TITLE
debug value isn't set properly

### ISSUE THREAD

**Issue by mr-karan** [lmangani/cLoki#71]
I've set `DEBUG=false` in my container and verified as well, however I am still seeing the query logs which are at:

- https://github.com/lmangani/cLoki/blob/master/lib/db/clickhouse.js#L194-L205
- https://github.com/lmangani/cLoki/blob/7057932482e0d03cdc09409846cb04aaa405309e/lib/handlers/push.js#L85
- https://github.com/lmangani/cLoki/blob/7057932482e0d03cdc09409846cb04aaa405309e/lib/handlers/push.js#L106

**Comment by Dletta** [comment]
Hi @mr-karan,

Thank you for your contribution. I will test it and merge it once it's confirmed.

Thank you again!!

**Comment by lmangani** [comment]
Hello @mr-karan 
The DEBUG value (like most other ENV bool options) is `false` by default and true when set to any string/int/variable. 
This is by "KISS" design since almost no config platform that's not JSON based can pass an actual boolean.

```
const debug = process.env.DEBUG || false
```

**Comment by mr-karan** [comment]
Noted. 

I think then this should be removed: https://github.com/lmangani/cLoki/blob/master/docker/docker-compose.yml#L53 as it's confusing.

**Comment by lmangani** [comment]
@mr-karan indeed that's a wrong example, sorry - we will refresh and move those examples into a separate repository next
