### ISSUE TITLE
Question: How's timestamp ordering handled

### ISSUE THREAD

**Issue by mr-karan** [lmangani/cLoki#73]
This is more of a question, than a bug report. 

I'm curious how Out of Order Timestamp events are handled in cLoki. Recently, Grafana Loki 2.4 release came with a [feature](https://grafana.com/blog/2021/09/16/avoid-dropped-logs-due-to-out-of-order-timestamps-with-a-new-loki-feature/) that by default enables to send the stream in any order, as long as it's recent than the chunk max age. 

I saw a few out of order event errors in my vector pipeline and I'm curious is that still a restriction in cLoki? For Loki, from what I understood it was because of their architecture of chunk/index store, but do we have this restrictions even with Clickhouse storage backend? 

Thanks 👍

**Comment by lmangani** [comment]
Thanks for the great question! We're proud to confirm cLoki does not suffer from the same design limitation and out-of-order / older logs are happily stored in clickhouse w/o side effects

**Comment by Bingmang** [comment]
I saw a few event errors in my vector pipeline too.

The loki is the qryn, the loki-local is the grafana/loki.

Don't know how to debug this, there is no warning or error log in qryn.

<img width="1067" alt="image" src="https://user-images.githubusercontent.com/19223221/176404245-c3cd9e8c-f917-4d96-a69d-15f7f14795c1.png">

**Comment by lmangani** [comment]
Hey @Bingmang could you share any of those errors? We'll try to replicate it if we have elements to do so.
