### ISSUE TITLE
cLoki line_format difference from Loki

### ISSUE THREAD

**Issue by xaled1** [lmangani/cLoki#84]
Hi,

Is it intentional and if yes, then why there is a difference in cLoki line_format with a dot compared to Loki without a dot?

Loki: line_format "{{.labelname}}"
cLoki: line_format "{{labelname}}"

**Comment by Dletta** [comment]
@xaled1 Thanks for the question.

Whenever possible we stay close to Loki API. Underneath we simply select the labelname we already extracted from the log. 

I can only guess why Loki adds the dot here, but it's more intuitive and in our system it's not necessary to add a dot in front of the label

**Comment by Dletta** [comment]
@xaled1 Thanks for the question.

Whenever possible we stay close to Loki API. Underneath we simply select the labelname we already extracted from the log. 

I can only guess why Loki adds the dot here, but it's more intuitive and in our system it's not necessary to add a dot in front of the label, so we didn't add it.

**Comment by xaled1** [comment]
I get that it is easier not to have a dot, but it breaks the interoperability between cLoki and Loki without a hard reason.
It would be good ro have the interface the same to port Loki based LogQL to cLoki without issues.

**Comment by lmangani** [comment]
@xaled1 absolutely, expect the next major version will provide 1:1 compatibility with LogQL as well as our extensions

**Comment by lmangani** [comment]
@akvlad can this difference be "masked" in the parser striping out dots as a temp compatibility measure until the next major?

**Comment by xaled1** [comment]
Yes, we can use at as a workaround.
Do you have a rough time plan for the next major release?

**Comment by akvlad** [comment]
I'll try to create a solution.

**Comment by akvlad** [comment]
Hello @xaled1 . We have a possible solution for you. It is in the https://github.com/lmangani/cLoki/tree/original_line_format branch.
Feel free to check. As far as it is a non-master branch highly experimental feature, we don't support backwards compatibility for it. So please play carefully. :)

**Comment by xaled1** [comment]
Thank you. Let me check it and get back to you.

**Comment by lmangani** [comment]
This change has been merged to master - please upgrade and let us know if you notice any inconsistencies. 

Thanks for your report and time!

**Comment by xaled1** [comment]
We have tested it and have not found any issues so far. 
Thank you and have good holidays!

**Comment by lmangani** [comment]
Thanks @xaled1
